### ISSUE TITLE
Uncaught ReflectionException: Class think\Config does not exist

### ISSUE THREAD

**Issue by hinet** [zz-studio/think-addons#13]
thinkphp6.0.3安装时出现以下错误：

`PHP Fatal error:  Uncaught ReflectionException: Class think\Config does not exist in E:\wwwroot\oneshop\vendor\topthink\framework\src\think\Container.php:374
Stack trace:
#0 E:\wwwroot\oneshop\vendor\topthink\framework\src\think\Container.php(374): ReflectionClass->__construct('think\\Config')
#1 E:\wwwroot\oneshop\vendor\topthink\framework\src\think\Container.php(250): think\Container->invokeClass('think\\Config', Array)
#2 E:\wwwroot\oneshop\vendor\topthink\framework\src\think\Container.php(130): think\Container->make('think\\Config')
#3 E:\wwwroot\oneshop\vendor\topthink\framework\src\think\Container.php(508): think\Container->get('config')
#4 E:\wwwroot\oneshop\vendor\topthink\framework\src\think\App.php(511): think\Container->__get('config')
#5 E:\wwwroot\oneshop\vendor\topthink\framework\src\think\App.php(420): think\App->load()
#6 E:\wwwroot\oneshop\vendor\topthink\framework\src\think\Console.php(95): think\App->initialize()
#7 [internal function]: think\Console->__construct(Object(think\App))
#8 E:\wwwroot\oneshop\vend in E:\wwwroot\oneshop\vendor\topthink\framework\src\think\Container.php on line 377`

请问如何解决

**Comment by hinet** [comment]
此问题已解决，将composer更新至最新版本即可
